‎name: Build APK
‎
‎on:
‎  push:
‎    branches:
‎      - main
‎
‎jobs:
‎  build:
‎    runs-on: ubuntu-latest
‎
‎    steps:
‎      - name: Checkout Repository
‎        uses: actions/checkout@v4
‎
‎      - name: Setup JDK 17
‎        uses: actions/setup-java@v4
‎        with:
‎          distribution: temurin
‎          java-version: 17
‎
‎      - name: Grant Gradle Permission
‎        run: chmod +x gradlew
‎
‎      - name: Build Debug APK
‎        run: ./gradlew assembleDebug
‎
‎      - name: Upload APK
‎        uses: actions/upload-artifact@v4
‎        with:
‎          name: app-debug-apk
‎          path: app/build/outputs/apk/debug/app-debug.apk
‎
